name: charter_project
repository: https://github.com/charter-projects/charter-project

ide:
  intellij:
    enabled: false

packages:
  - packages/*
  - localization

command:
  environment:
    sdk: ">=3.2.0 <4.0.0"
    flutter: ">=1.17.0"

  bootstrap:
    # Add dependencies that need to be synced here
    dependencies:
      auto_mappr_annotation: ^2.1.0
      bloc: ^8.1.2
      copy_with_extension: ^5.0.4
      equatable: ^2.0.5
      flutter_bloc: ^8.1.3
      json_annotation: ^4.8.1
      slang_flutter: ^3.28.0
      slang: ^3.28.0

    dev_dependencies:
      auto_mappr: ^2.2.0
      build_runner: ^2.4.6
      commitlint_cli: ^0.7.1
      copy_with_extension_gen: ^5.0.4
      json_serializable: ^6.7.1

    hooks:
      pre: melos clean

  version:
    branch: version
    includeScopes: true
    includeCommitId: true
    linkToCommits: true
    workspaceChangelog: true
    updateGitTagRefs: true
    fetchTags: true
    message: |
      chore(versioning): Assembled package releases 🎉

      {new_package_versions}
    changelogs:
      - path: CHANGELOG.md
        description: |
          All notable changes to packages will be documented in this file.
        packageFilters:
          scope: packages/*

scripts:
  analyze:
    exec: dart analyze --fatal-infos .
    description: Run `dart analyze` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dirExists:
        - lib

  fix:
    exec: dart fix --apply
    description: Run `dart fix --apply` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dirExists:
        - lib

  test:
    exec: flutter test
    description: Run `flutter test` in a selected package. Includes prompt for packages.
    packageFilters:
      dirExists:
        - test

  pub:get:
    exec: flutter pub get
    description: Run `flutter pub get` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dirExists:
        - lib

  pub:upgrade:
    exec: flutter pub upgrade
    description: Run `dart pub upgrade` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dirExists:
        - lib

  build_runner:
    exec: dart run build_runner build --delete-conflicting-outputs
    description: Run `dart run build_runner build --delete-conflicting-outputs` in selected or all packages. Includes prompt for packages.
    packageFilters:
      dependsOn: "build_runner"

  flutter:clean:
    exec: >-
      flutter clean
      && flutter pub get
    description: Cleans all flutter cache and build files
    concurrency: 1
    packageFilters:
      flutter: true

  i18n:
    exec: dart run slang
    description: Generate flutter locates from slang json files
    packageFilters:
      dependsOn: "slang"
      fileExists:
        - slang.yaml

  # CI Jobs
  ci:quality:
    run: |
      melos run analyze --no-select
      melos run test --no-select
    description: Run tests and analyze in all modules available without prompting for modules.

  ci:l10n:
    run: |
      melos run l10n:gen --no-select
    description: Generates localization files in all modules that contain localization files without prompting for modules.
