name: charter_project
description: The root workspace for the Charter Project
version: 1.0.0
repository: https://github.com/charter-projects/charter-project
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  commitlint_cli: ^0.7.1
  husky: ^0.1.6
  melos: ^3.4.0
